apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pc-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
